on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

name: CI
jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm ci --ignore-scripts --audit=false

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm ci --ignore-scripts --audit=false
        run: npm run build

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm ci --ignore-scripts --audit=false
        run: npm run lint

  test:
    name: Test Code
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm ci --ignore-scripts --audit=false
        run: npm run test
