on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Continuous Integration
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          scope: '@lego'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn workspaces run lint
      - name: Test
        run: yarn workspaces run test
      - name: Build
        run: yarn workspaces run build
