on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          scope: '@lego'
      - name: Install dependencies
        run: npm ci --ignore-scripts --audit=false
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
        run: npm run release
